const certificate_3rd = [
    {
      "Name": "ADM Responsible Soybean Standard",
      "Website": "https://www.adm.com/en-us/",
      "Logo": "https://www.adm.com/globalassets/header-and-footer/adm-logo-header-large.png",
      "eScore": 44,
      "sScore": 41,
      "gScore": "15",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "Aluminium Stewardship Initiative",
      "Website": "https://aluminium-stewardship.org/",
      "Logo": "https://aluminium-stewardship.org/wp-content/themes/asiportal/assets/images/asi-logo.svg",
      "eScore": 37,
      "sScore": 23,
      "gScore": "40",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 50000
    },
    {
      "Name": "Aquaculture Stewardship Council - ASC Pangasius",
      "Website": "https://asc-aqua.org/",
      "Logo": "https://asc-aqua.org/wp-content/uploads/2023/04/logo-asc.svg",
      "eScore": 1,
      "sScore": 63,
      "gScore": "36",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 35000
    },
    {
      "Name": "Aquaculture Stewardship Council - ASC Salmon",
      "Website": "https://asc-aqua.org/",
      "Logo": "https://asc-aqua.org/wp-content/uploads/2023/04/logo-asc.svg",
      "eScore": 42,
      "sScore": 21,
      "gScore": "37",
      "Price":100,
      "Lowest Price": 20000,
      "Highest Price": 50000
    },
    {
      "Name": "Aquaculture Stewardship Council - ASC Shrimp",
      "Website": "https://asc-aqua.org/",
      "Logo": "https://asc-aqua.org/wp-content/uploads/2023/04/logo-asc.svg",
      "eScore": 32,
      "sScore": 25,
      "gScore": "43",
      "Price":100,
      "Lowest Price": 15000,
      "Highest Price": 40000
    },
    {
      "Name": "Aquaculture Stewardship Council - ASC Tilapia",
      "Website": "https://asc-aqua.org/",
      "Logo": "https://asc-aqua.org/wp-content/uploads/2023/04/logo-asc.svg",
      "eScore": 44,
      "sScore": 49,
      "gScore": "7",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 30000
    },
    {
      "Name": "ASC - Camarones/Langostino",
      "Website": "https://asc-aqua.org/",
      "Logo": "https://asc-aqua.org/wp-content/uploads/2023/04/logo-asc.svg",
      "eScore": 4,
      "sScore": 83,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 15000,
      "Highest Price": 40000
    },
    {
      "Name": "ASC-MSC Seaweed (Algae)",
      "Website": "https://asc-aqua.org/producers/asc-standards/seaweed-standard/",
      "Logo": "https://asc-aqua.org/wp-content/uploads/2023/04/logo-asc.svg",
      "eScore": 57,
      "sScore": 41,
      "gScore": "2",
      "Price":100,
      "Lowest Price": 10500,
      "Highest Price": 50000
    },
    {
      "Name": "Agricultura Sustentable Certificada + Module on Non-conversion",
      "Website": "https://www.aapresid.org.ar/blog/certificaciones-protocolo-ASC",
      "Logo": "https://www.aapresid.org.ar/img/certificaciones/asc.png",
      "eScore": 43,
      "sScore": 45,
      "gScore": "12",
      "Price":100,
      "Lowest Price": 7000,
      "Highest Price": 25000
    },
    {
      "Name": "Better Cotton",
      "Website": "https://bettercotton.org/",
      "Logo": "https://bettercotton.org/wp-content/uploads/2021/05/BC_white.svg",
      "eScore": 8,
      "sScore": 5,
      "gScore": "87",
      "Price":100,
      "Lowest Price": 6000,
      "Highest Price": 20000
    },
    {
      "Name": "Bio-Knospe",
      "Website": "https://www.bio-suisse.ch/de.html",
      "Logo": "https://www.bio-suisse.ch/dam/jcr:042a8428-1b1b-415f-baae-502b4b3ce76a/logo.svg",
      "eScore": 40,
      "sScore": 42,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 18000
    },
    {
      "Name": "BRCGS Food Safety",
      "Website": "https://www.brcgs.com/",
      "Logo": "https://agfocert.com/wp-content/uploads/ETRS-0-1024x190.jpg",
      "eScore": 76,
      "sScore": 8,
      "gScore": "16",
      "Price":100,
      "Lowest Price": 8000,
      "Highest Price": 25000
    },
    {
      "Name": "BRCGS Inocuidad Alimentaria",
      "Website": "https://www.brcgs.com/",
      "Logo": "https://agfocert.com/wp-content/uploads/ETRS-0-1024x190.jpg",
      "eScore": 72,
      "sScore": 0,
      "gScore": "28",
      "Price":100,
      "Lowest Price": 8000,
      "Highest Price": 25000
    },
    {
      "Name": "Bunge Pro-S Assuring Sustainable Sourcing",
      "Website": "https://www.bunge.com/",
      "Logo": "https://delivery.bunge.com/-/jssmedia/Feature/Components/Basic/Icons/NewLogo.ashx?h=120&iar=0&w=40&hash=8203337AD16ABC84A0C07E5B627782E0",
      "eScore": 77,
      "sScore": 0,
      "gScore": "23",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 30000
    },
    {
      "Name": "Delinat",
      "Website": "https://www.delinat.com/",
      "Logo": "https://www.delinat.com/img/global/Delinat_Logo-2x.png",
      "eScore": 65,
      "sScore": 0,
      "gScore": "35",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "Donau Soja",
      "Website": "https://www.donausoja.org/",
      "Logo": "https://www.donausoja.org/wp-content/uploads/2023/06/europesoja_donausoja_logo_230.png",
      "eScore": 65,
      "sScore": 0,
      "gScore": "35",
      "Price":100,
      "Lowest Price": 4000,
      "Highest Price": 15000
    },
    {
      "Name": "ECO PASSPORT by OEKO-TEX\u00ae",
      "Website": "https://www.oeko-tex.com/en/our-standards/oeko-tex-eco-passport",
      "Logo": "https://logowik.com/content/uploads/images/oeko-tex-eco-passport-standart9630.logowik.com.webp",
      "eScore": 59,
      "sScore": 17,
      "gScore": "25",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 15000
    },
    {
      "Name": "EPEAT",
      "Website": "https://www.epeat.net/",
      "Logo": "https://us.qcells.com/wp-content/uploads/2024/05/EPEAT-Green-Mark_Registered.webp",
      "eScore": 58,
      "sScore": 5,
      "gScore": "37",
      "Price":100,
      "Lowest Price": 7000,
      "Highest Price": 30000
    },
    {
      "Name": "EarthCheck Company Standard",
      "Website": "https://earthcheck.org/wp-content/uploads/2022/12/FINAL-MASTER-EarthCheck-Company-Standard-V4.1-25-August-20-January-2022-release-DZ.pdf",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzFQy6-NhdhUFr1Rg662uJjMXCHrlR95ngJGLUCNpfxirkYcbfaiNZyXY3fuj2Dwav2-0&usqp=CAU",
      "eScore": 41,
      "sScore": 32,
      "gScore": "27",
      "Price":100,
      "Lowest Price": 7000,
      "Highest Price": 30000
    },
    {
      "Name": "Europe Soya",
      "Website": "https://www.donausoja.org/certification-inspection/europe-soya-standard/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0TS9_DbzBDSPcYszktT1uTRM_NSfnN5h3bA&s",
      "eScore": 0,
      "sScore": 87,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "European Feed ingredients Safety Certification - EFISC",
      "Website": "https://www.efisc-gtp.eu/",
      "Logo": "https://impakter.com/index/wp-content/uploads/2021/07/download.jpeg",
      "eScore": 32,
      "sScore": 18,
      "gScore": "50",
      "Price":100,
      "Lowest Price": 8000,
      "Highest Price": 25000
    },
    {
      "Name": "Fair for Life",
      "Website": "https://www.fairforlife.org/pmws/indexDOM.php?client_id=fairforlife&page_id=ffl&lang_iso639=en",
      "Logo": "https://www.duasrodas.com/site/uploads/2023/03/Fair-for-life-300x300.jpg",
      "eScore": 2,
      "sScore": 84,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 6000,
      "Highest Price": 20000
    },
    {
      "Name": "Fairtrade International Textile Standard",
      "Website": "https://www.fairtrade.net/standard/textile",
      "Logo": "https://cdn11.bigcommerce.com/s-n2yusj/images/stencil/640w/products/951/5531/fairtrade__53767.1532755301.500.659__34575.1643944000.jpg?c=2",
      "eScore": 23,
      "sScore": 59,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 6000,
      "Highest Price": 25000
    },
    {
      "Name": "Fairtrade International - Gold Standard",
      "Website": "https://www.fairtrade.net/standard/gold",
      "Logo": "https://cdn11.bigcommerce.com/s-n2yusj/images/stencil/640w/products/951/5531/fairtrade__53767.1532755301.500.659__34575.1643944000.jpg?c=2",
      "eScore": 14,
      "sScore": 67,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 8000,
      "Highest Price": 30000
    },
    {
      "Name": "Fair Wage Network",
      "Website": "https://fair-wage.com/",
      "Logo": "https://fair-wage.com/wp-content/uploads/2018/03/fw_logo_396.png",
      "eScore": 38,
      "sScore": 45,
      "gScore": "16",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "FairWild",
      "Website": "https://www.fairwild.org/fairwild-certification",
      "Logo": "https://images.squarespace-cdn.com/content/v1/5bec424b297114f64cb908d8/1542210593941-9GG23EZN9JBPOWBS21IR/fairwild-logo.png?format=500w",
      "eScore": 23,
      "sScore": 59,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "FEMAS Responsible Sourcing Module 2021",
      "Website": "https://www.agindustries.org.uk/resource/aic-femas-responsible-sourcing-module-2021.html",
      "Logo": "https://www.agindustries.org.uk/static/1a7c347b-2962-415f-b00d6b128dc03fe7/0c489aba-8403-4e81-bd00861aac1cc54d/toc_d333720560e279be8ea4c96c6f19c1f6/FEMAS-logo.png",
      "eScore": 16,
      "sScore": 73,
      "gScore": "11",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 15000
    },
    {
      "Name": "FLORIMARK GTP",
      "Website": "https://my-mps.com/diensten/florimark-gtp/?lang=en",
      "Logo": "https://my-mps.com/wp-content/themes/mps/assets/images/general/MPS_logo.svg",
      "eScore": 39,
      "sScore": 47,
      "gScore": "14",
      "Price":100,
      "Lowest Price": 4000,
      "Highest Price": 15000
    },
    {
      "Name": "Food Safety System Certification 22000",
      "Website": "https://www.fssc.com/schemes/fssc-22000/",
      "Logo": "https://www.merieuxnutrisciences.com/na/wp-content/uploads/2022/01/fssc.png",
      "eScore": 6,
      "sScore": 53,
      "gScore": "42",
      "Price":100,
      "Lowest Price": 7000,
      "Highest Price": 30000
    },
    {
      "Name": "Food Security Standard",
      "Website": "https://foodsecuritystandard.org/en/home/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiY4_MjVxK0XcDYBLaAYbfcsb-8PoiXiaDrw&s",
      "eScore": 38,
      "sScore": 44,
      "gScore": "17",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 25000
    },
    {
      "Name": "For Life",
      "Website": "https://www.fairforlife.org/pmws/indexDOM.php?client_id=fairforlife&page_id=fl&lang_iso639=en",
      "Logo": "https://seasonallyfresh.com/wp-content/uploads/2017/05/For-LIfe-Cert.png",
      "eScore": 66,
      "sScore": 16,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "Forest Stewardship Council\u00ae - FSC\u00ae - Chain of Custody",
      "Website": "https://fsc.org/en/chain-of-custody-certification",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUO05kNiY-XiiZff-oGW88gO91MwIOwKuMsw&s",
      "eScore": 6,
      "sScore": 64,
      "gScore": "31",
      "Price":100,
      "Lowest Price": 4000,
      "Highest Price": 15000
    },
    {
      "Name": "Forest Stewardship Council\u00ae - FSC\u00ae - Forest Management",
      "Website": "https://fsc.org/en/forest-managers",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUO05kNiY-XiiZff-oGW88gO91MwIOwKuMsw&s",
      "eScore": 44,
      "sScore": 17,
      "gScore": "39",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 35000
    },
    {
      "Name": "FOS - Wild - Generic Sustainable fishing Requirements",
      "Website": "https://friendofthesea.org/wp-content/uploads/Minh_Dang_Company_LTD2015_Wild_report.pdf",
      "Logo": "https://banner2.cleanpng.com/20180725/zec/kisspng-friend-of-the-sea-sustainable-fishery-conservation-5b58a015b8bad6.7925866015325348057567.jpg",
      "eScore": 57,
      "sScore": 17,
      "gScore": "26",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "Friend of the Sea - Chain of Custody",
      "Website": "https://friendofthesea.org/standard-improvement/",
      "Logo": "https://banner2.cleanpng.com/20180725/zec/kisspng-friend-of-the-sea-sustainable-fishery-conservation-5b58a015b8bad6.7925866015325348057567.jpg",
      "eScore": 38,
      "sScore": 13,
      "gScore": "49",
      "Price":100,
      "Lowest Price": 4000,
      "Highest Price": 15000
    },
    {
      "Name": "Friend of the Sea (FOS) - Marine Aquaculture",
      "Website": "https://friendofthesea.org/sustainable-standards-and-certifications/sustainable-aquaculture/",
      "Logo": "https://banner2.cleanpng.com/20180725/zec/kisspng-friend-of-the-sea-sustainable-fishery-conservation-5b58a015b8bad6.7925866015325348057567.jpg",
      "eScore": 0,
      "sScore": 92,
      "gScore": "8",
      "Price":100,
      "Lowest Price": 8000,
      "Highest Price": 30000
    },
    {
      "Name": "Global Recycled Standard - GRS",
      "Website": "https://textileexchange.org/recycled-claim-global-recycled-standard/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSndOwB0O-8PPV-XhjEkcrvVGvGaaiHvg54pQ&s",
      "eScore": 42,
      "sScore": 46,
      "gScore": "11",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 20000
    },
    {
      "Name": "GLOBALG.A.P. Aquaculture",
      "Website": "https://www.globalgap.org/what-we-offer/solutions/ifa-aquaculture/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1LyyX4m-i0J92eVVCxFrHuUdFaxWFdTpqg&s",
      "eScore": 36,
      "sScore": 19,
      "gScore": "44",
      "Price":100,
      "Lowest Price": 6000,
      "Highest Price": 25000
    },
    {
      "Name": "GLOBALG.A.P. Floriculture",
      "Website": "https://www.globalgap.org/what-we-offer/solutions/ifa-flowers-and-ornamentals/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1LyyX4m-i0J92eVVCxFrHuUdFaxWFdTpqg&s",
      "eScore": 100,
      "sScore": 0,
      "gScore": "0",
      "Price":100,
      "Lowest Price": 4000,
      "Highest Price": 15000
    },
    {
      "Name": "GLOBALG.A.P. Integrated Farm Assurance Smart \u2013 principles and criteria for fruit and vegetables",
      "Website": "https://www.globalgap.org/what-we-offer/solutions/ifa-fruit-and-vegetables/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1LyyX4m-i0J92eVVCxFrHuUdFaxWFdTpqg&s",
      "eScore": 18,
      "sScore": 44,
      "gScore": "38",
      "Price":100,
      "Lowest Price": 4000,
      "Highest Price": 15000
    },
    {
      "Name": "GlobalG.A.P. Livestock",
      "Website": "https://www.globalgap.org/news/globalgap-secures-a-continuity-option-for-the-ifa-livestock-scope/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1LyyX4m-i0J92eVVCxFrHuUdFaxWFdTpqg&s",
      "eScore": 30,
      "sScore": 0,
      "gScore": "69",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 2000
    },
    {
      "Name": "GLOBALG.A.P. Risk Assessment on Social Practice (GRASP)",
      "Website": "https://www.globalgap.org/what-we-offer/solutions/grasp/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ1d9qPvnhTKNvzbTr8dCchy7xOZMxfq0AkA&s",
      "eScore": 14,
      "sScore": 15,
      "gScore": "71",
      "Price":100,
      "Lowest Price": 0,
      "Highest Price": 0
    },
    {
      "Name": "GMP+",
      "Website": "https://www.gmpplus.org/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTThJ3MvGoNRIiL-mhh13Hq6DCytnHXWiCXuA&s",
      "eScore": 64,
      "sScore": 23,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Guide on Social Responsibility for Chinese Int Contractors",
      "Website": "https://asiasociety.org/sites/default/files/inline-files/2021_CHINCA_Draft20Revisions20to20Guide20on20Social20Responsibility20for20Chinese20International20Contractors_E.pdf",
      "Logo": "https://emsdialogues.org/wp-content/uploads/2019/12/CHINCA_Guide-on-Social-Responsibility-for-Chinese-International-Contractors-pdf-352x480.jpg",
      "eScore": 18,
      "sScore": 44,
      "gScore": "38",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 10000
    },
    {
      "Name": "ICEC TS 410",
      "Website": "https://www.icec.it/en/certifications/product-economic-sustainability/leather-traceability-certification",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf25DVYijBVU58FHm8hwdiWbPYUdXEalJnQg&s",
      "eScore": 38,
      "sScore": 41,
      "gScore": "21",
      "Price":100,
      "Lowest Price": 3000,
      "Highest Price": 8000
    },
    {
      "Name": "International Council on Mining and Metals",
      "Website": "https://www.icmm.com/",
      "Logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/ICMM_Logo.png/1200px-ICMM_Logo.png",
      "eScore": 32,
      "sScore": 38,
      "gScore": "30",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 0
    },
    {
      "Name": "LEAF Marque",
      "Website": "https://leaf.eco/leafmarque/about",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIgutJZge1HvMDzBA3geZoLKzDE0IbXaNqxQ&s",
      "eScore": 52,
      "sScore": 20,
      "gScore": "28",
      "Price":100,
      "Lowest Price": 0,
      "Highest Price": 0
    },
    {
      "Name": "Low Carbon Timber (Holz Von Hier)",
      "Website": "https://www.holz-von-hier.eu/fuer-unternehmen/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrcDPWE7ozCwezOu4W0P7A9lmP2IKc02vs3A&s",
      "eScore": 68,
      "sScore": 2,
      "gScore": "30",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 0
    },
    {
      "Name": "Marine Stewardship Council - MSC",
      "Website": "https://www.msc.org/",
      "Logo": "https://upload.wikimedia.org/wikipedia/en/3/3e/MSC_ecolabel.png",
      "eScore": 46,
      "sScore": 37,
      "gScore": "17",
      "Price":100,
      "Lowest Price": 10000,
      "Highest Price": 15000
    },
    {
      "Name": "MarinTrust Standard",
      "Website": "https://www.marin-trust.com/marintrust-factory-standard/version-2",
      "Logo": "https://www.marin-trust.com/sites/marintrust/files/styles/large/public/2021-12/MT20logo20small20PNG_0.png?itok=nlxrE7b4",
      "eScore": 53,
      "sScore": 35,
      "gScore": "12",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 7000
    },
    {
      "Name": "MPS-GAP",
      "Website": "https://my-mps.com/diensten/mps-gap/?lang=en",
      "Logo": "https://my-mps.com/wp-content/themes/mps/assets/images/general/MPS_logo.svg",
      "eScore": 38,
      "sScore": 41,
      "gScore": "21",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 2000
    },
    {
      "Name": "MPS-Socially Qualified (SQ)",
      "Website": "https://my-mps.com/diensten/mps-socially-qualified/?lang=en",
      "Logo": "https://my-mps.com/wp-content/themes/mps/assets/images/general/MPS_logo.svg",
      "eScore": 96,
      "sScore": 0,
      "gScore": "4",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 1500
    },
    {
      "Name": "Naturland Standards on Production",
      "Website": "https://www.naturland.de/images/01_naturland/_en/Standards/Naturland-Standards-on-Production.pdf",
      "Logo": "https://quirantefruits.com/wp-content/uploads/2021/11/Naturland-300x225-1.png",
      "eScore": 37,
      "sScore": 23,
      "gScore": "40",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 3000
    },
    {
      "Name": "Naturland Textile",
      "Website": "https://www.naturland.de/en/naturland/what-we-stand-for/quality/naturland-standards.html?view=article&id=4077&catid=262",
      "Logo": "https://quirantefruits.com/wp-content/uploads/2021/11/Naturland-300x225-1.png",
      "eScore": 28,
      "sScore": 57,
      "gScore": "15",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Naturtextil IVN certified BEST",
      "Website": "https://www.controlunion.com/certification-program/ivn-naturtextil/",
      "Logo": "https://impakter.com/pro/wp-content/uploads/2020/06/IVNBEST_4C_maxi-768x750.jpg",
      "eScore": 64,
      "sScore": 5,
      "gScore": "31",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 3000
    },
    {
      "Name": "Nordic Ecolabel - Laundry Detergents",
      "Website": "https://www.nordic-swan-ecolabel.org/criteria/laundry-detergents-for-professional-use-093/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTChKE1wENx0d7dQsOA5VrflxuKarWUSfO02QuHKx5GUONyAFjhFNblqP3VYy0NdT_YpmY&usqp=CAU",
      "eScore": 55,
      "sScore": 0,
      "gScore": "45",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 8000
    },
    {
      "Name": "Nordic Ecolabel - Paper",
      "Website": "https://www.nordic-swan-ecolabel.org/pulp-paper-declaration-portal/the-msa-portal/paper-and-board-suppliers/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTChKE1wENx0d7dQsOA5VrflxuKarWUSfO02QuHKx5GUONyAFjhFNblqP3VYy0NdT_YpmY&usqp=CAU",
      "eScore": 54,
      "sScore": 17,
      "gScore": "-7000%",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 8000
    },
    {
      "Name": "OEKO-TEX\u00ae STANDARD 100",
      "Website": "https://www.oeko-tex.com/en/our-standards/oeko-tex-standard-100",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBUBs3tVfbC4jfMEhNHKp10-ZzPCwVh1uxlg&s",
      "eScore": 33,
      "sScore": 48,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 0,
      "Highest Price": 0
    },
    {
      "Name": "OEKO-TEX\u00ae LEATHER STANDARD",
      "Website": "https://www.oeko-tex.com/en/our-standards/oeko-tex-leather-standard",
      "Logo": "https://www.centrocot.it/wp-content/uploads/2022/11/OEKO-TEX_LS_Logo_rgb-213x300.png",
      "eScore": 40,
      "sScore": 41,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 0,
      "Highest Price": 0
    },
    {
      "Name": "OEKO-TEX\u00ae MADE IN GREEN",
      "Website": "https://www.oeko-tex.com/en/our-standards/oeko-tex-made-in-green",
      "Logo": "https://logowik.com/content/uploads/images/oeko-tex-made-in-green-standart7994.logowik.com.webp",
      "eScore": 40,
      "sScore": 41,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 0,
      "Highest Price": 0
    },
    {
      "Name": "OEKO-TEX\u00ae RESPONSIBLE BUSINESS",
      "Website": "https://www.oeko-tex.com/en/our-standards/oeko-tex-responsible-business",
      "Logo": "https://www.centrocot.it/wp-content/uploads/2022/11/OEKO-TEX_RB_Logo_rgb.png",
      "eScore": 24,
      "sScore": 51,
      "gScore": "25",
      "Price":100,
      "Lowest Price": 5000,
      "Highest Price": 10000
    },
    {
      "Name": "On The Way To PlanetProof for Plant Products in Central Europe",
      "Website": "https://www.planetproof.eu/en/",
      "Logo": "https://impakter.com/index/wp-content/uploads/2021/07/PlanetProof_Fine_RGB_150px.png",
      "eScore": 76,
      "sScore": 6,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "PEFC International - Chain of Custody of Forest Based Products",
      "Website": "https://standards.pefc.org/the-standards/chain-of-custody",
      "Logo": "https://navigator-paper.com/navigator/brand/images/sustainability/pefc.png",
      "eScore": 63,
      "sScore": 18,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 1500
    },
    {
      "Name": "Predator Friendly\u00ae Standards",
      "Website": "https://wildlifefriendly.org/standards/",
      "Logo": "https://impakter.com/index/wp-content/uploads/2021/07/Unknown.jpg",
      "eScore": 48,
      "sScore": 36,
      "gScore": "16",
      "Price":100,
      "Lowest Price": 250,
      "Highest Price": 0
    },
    {
      "Name": "Rainforest Alliance - 2020",
      "Website": "https://www.rainforest-alliance.org/for-business/2020-certification-program/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8rC6pKqiVcP96eO_hgq7CeHcMnWbr5MZhqw&s",
      "eScore": 46,
      "sScore": 13,
      "gScore": "41",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 2000
    },
    {
      "Name": "Red Tractor Combinable Crops and Sugar Beet Standards",
      "Website": "https://redtractorassurance.org.uk/standard-categories/crops/",
      "Logo": "https://redtractorassurance.org.uk/wp-content/uploads/2021/07/RedTractor_CertifiedStandards_TRACEABLE_Landscape_Logo_CMYK-01-1024x495.png",
      "eScore": 20,
      "sScore": 59,
      "gScore": "21",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 1000
    },
    {
      "Name": "Red Tractor Fresh Produce Standards",
      "Website": "https://redtractorassurance.org.uk/standard-categories/fresh-produce/",
      "Logo": "https://redtractorassurance.org.uk/wp-content/uploads/2021/07/RedTractor_CertifiedStandards_TRACEABLE_Landscape_Logo_CMYK-01-1024x495.png",
      "eScore": 19,
      "sScore": 59,
      "gScore": "22",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 1000
    },
    {
      "Name": "Responsible Recycling Standard for Electronics Recyclers",
      "Website": "https://sustainableelectronics.org/r2/",
      "Logo": "https://impakter.com/index/wp-content/uploads/2021/07/download-3.png",
      "eScore": 21,
      "sScore": 61,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 3000,
      "Highest Price": 6000
    },
    {
      "Name": "Roundtable on Sustainable Biomaterials EU RED Standard",
      "Website": "https://rsb.org/certification/certification-schemes/rsb-eu-red-fuel-certification/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUCotVJwCFP5DOOZW7CW4uwQ8mSODNnjX3Fw&s",
      "eScore": 29,
      "sScore": 46,
      "gScore": "25",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "Roundtable on Sustainable Palm Oil - Principles and Criteria",
      "Website": "https://rspo.org/as-an-organisation/our-standards/",
      "Logo": "https://cdn.scsglobalservices.com/files/SCS_RSPO_logo1_1.png?VersionId=3S9Ofo3CG4upT1sRI6j_AHufZsn1m5Kw",
      "eScore": 1,
      "sScore": 0,
      "gScore": "99",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 4000
    },
    {
      "Name": "RSB Standard (Roundtable on Sustainable Biomaterials)",
      "Website": "https://rsb.org/",
      "Logo": "https://impakter.com/index/wp-content/uploads/2021/07/rsb.png",
      "eScore": 0,
      "sScore": 89,
      "gScore": "11",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "SODRU Sustainable Soy",
      "Website": "https://sodrugestvo.com.br/wp-content/uploads/2023/05/Sodrugestvo-Sustainable-Soy-ver-2-27-April-2023.pdf",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtSOe9cr2vQM_Hi1jWl8kcRjmzxTMhg_ZNPg&s",
      "eScore": 52,
      "sScore": 28,
      "gScore": "20",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Soil Association organic standards- farming and growing",
      "Website": "https://www.soilassociation.org/our-standards/read-our-organic-standards/",
      "Logo": "https://www.cosmeticsdesign-europe.com/var/wrbm_gb_food_pharma/storage/images/_aliases/wrbm_large/5/1/2/3/7293215-5-eng-GB/Soil-Association-on-COSMOS-certification-Consider-long-term-strategy.jpg",
      "eScore": 27,
      "sScore": 56,
      "gScore": "17",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 1200
    },
    {
      "Name": "STeP by OEKO-TEX\u00ae",
      "Website": "https://www.oeko-tex.com/en/our-standards/oeko-tex-step",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUGPWp_5rRB5UkgKbXOCZ2nPoDY7E14z2CSg&s",
      "eScore": 10,
      "sScore": 0,
      "gScore": "90",
      "Price":100,
      "Lowest Price": 3000,
      "Highest Price": 5000
    },
    {
      "Name": "Sustainable Rice Platform",
      "Website": "https://sustainablerice.org/",
      "Logo": "https://media.licdn.com/dms/image/C4E0BAQHmDsyYVJWeXg/company-logo_200_200/0/1630649594854/sustainable_rice_platform_logo?e=2147483647&v=beta&t=oQX3lybQshfc15mckPgInpFfrGeDMl3FW-bkemw9B8w",
      "eScore": 52,
      "sScore": 42,
      "gScore": "6",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Sustainably Grown",
      "Website": "https://www.scsglobalservices.com/services/sustainably-grown-certification",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwmEy-fpfnsQWgcwvZHn7r4SzSeWwbCakIBg&s",
      "eScore": 53,
      "sScore": 0,
      "gScore": "47",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "Textile Exchange Global Recycled Standard",
      "Website": "https://textileexchange.org/recycled-claim-global-recycled-standard/",
      "Logo": "https://fibreguard.com/uploads/GRS-Color-logo-from-textile-exchange.png",
      "eScore": 54,
      "sScore": 40,
      "gScore": "6",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Textile Exchange Responsible Down Standard",
      "Website": "https://textileexchange.org/responsible-down-standard/",
      "Logo": "https://3blaws.s3.amazonaws.com/styles/carousel_2x/s3/images/TE_Logo_0.jpg",
      "eScore": 19,
      "sScore": 63,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "The Blue Angel - Detergents",
      "Website": "https://www.blauer-engel.de/en/productworld/laundry-detergent",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuMgx8beoq-cnxPypx_-8CcDfiv5YoaSXPDA&s",
      "eScore": 56,
      "sScore": 0,
      "gScore": "44",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "The Blue Angel - Leather",
      "Website": "https://www.blauer-engel.de/en/productworld/leather",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuMgx8beoq-cnxPypx_-8CcDfiv5YoaSXPDA&s",
      "eScore": 51,
      "sScore": 39,
      "gScore": "11",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "The Sustainable Beef & Lamb Assurance Scheme",
      "Website": "https://www.bordbia.ie/farmers-growers/get-involved/become-quality-assured/sustainable-beef-and-lamb-assurance-scheme-sblas/",
      "Logo": "https://highlandradio.com/wp-content/uploads/2015/03/bord_bia_logo.jpg",
      "eScore": 17,
      "sScore": 74,
      "gScore": "8",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 2000
    },
    {
      "Name": "The Sustainable Egg Assurance Scheme (SEAS)",
      "Website": "https://www.bordbia.ie/farmers-growers/get-involved/become-quality-assured/sustainable-egg-assurance-scheme-seas/#:~:text=The20SEAS20ensures20that20all,Flock20sourcing",
      "Logo": "https://highlandradio.com/wp-content/uploads/2015/03/bord_bia_logo.jpg",
      "eScore": 0,
      "sScore": 0,
      "gScore": "100",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 2000
    },
    {
      "Name": "The Sustainable Horticulture Assurance Scheme (SHAS)",
      "Website": "https://www.bordbia.ie/farmers-growers/get-involved/become-quality-assured/sustainable-horticulture-assurance-scheme-shas/#:~:text=Certification20to20the20SHAS20means,which20is20embracing20sustainable20practices.",
      "Logo": "https://highlandradio.com/wp-content/uploads/2015/03/bord_bia_logo.jpg",
      "eScore": 83,
      "sScore": 0,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 2000
    },
    {
      "Name": "Together for Sustainability AISBL (TfS)",
      "Website": "https://www.tfs-initiative.com/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBkoVfX3rcnXCyY11STvqZHR8MkH0BJ9FU2A&s",
      "eScore": 49,
      "sScore": 33,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 3000,
      "Highest Price": 6000
    },
    {
      "Name": "TourCert",
      "Website": "https://tourcert.org/es/",
      "Logo": "https://ecuadorandbeyond.wordpress.com/wp-content/uploads/2017/08/tourcert-logo1.png?w=300&h=300",
      "eScore": 38,
      "sScore": 46,
      "gScore": "15",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "T\u00dcV Rheinland - Green Product Mark - Furniture",
      "Website": "https://www.tuv.com/world/en/green-product-mark.html",
      "Logo": "https://www.tuv.com/content-media-files/master-content/services/products/1293-tuv-rheinland-green-product-mark/tuv-rheinland-green-product-mark-graphic-en_core_1_x.jpg",
      "eScore": 46,
      "sScore": 9,
      "gScore": "46",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 4000
    },
    {
      "Name": "T\u00dcV Rheinland Green Product Mark Textile",
      "Website": "https://www.tuv.com/world/en/green-product-mark.html",
      "Logo": "https://www.tuv.com/content-media-files/master-content/services/products/1293-tuv-rheinland-green-product-mark/tuv-rheinland-green-product-mark-graphic-en_core_1_x.jpg",
      "eScore": 42,
      "sScore": 3,
      "gScore": "54",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 4000
    },
    {
      "Name": "Unilever Sustainable Agriculture Code",
      "Website": "https://www.unilever.com/files/92ui5egz/production/555201fc976d5389fbdf9845099c15b61d1ceb53.pdf",
      "Logo": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Unilever.svg/1200px-Unilever.svg.png",
      "eScore": 52,
      "sScore": 0,
      "gScore": "48",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 4000
    },
    {
      "Name": "Union for Ethical BioTrade - UEBT",
      "Website": "https://uebt.org/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT0Md5Gw8k2_ckwKxxN4kneUP6cNlkdBRFEg&s",
      "eScore": 58,
      "sScore": 29,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 3000
    },
    {
      "Name": "USDA National Organic Program - NOP",
      "Website": "https://www.ams.usda.gov/about-ams/programs-offices/national-organic-program",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9qrK5nJ0zTO4QC4RaDos_9sq4IKlYy7QeNg&s",
      "eScore": 55,
      "sScore": 6,
      "gScore": "37",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 1500
    },
    {
      "Name": "Vitality Leaf",
      "Website": "https://globalecolabelling.net/organisation/vitality-leaf/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMrgw2qjkb0-OcNvSvDKw4cMpVrQ0taexYeQ&s",
      "eScore": 70,
      "sScore": 13,
      "gScore": "17",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Vitality Leaf for Fertilizers",
      "Website": "https://globalecolabelling.net/organisation/vitality-leaf/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMrgw2qjkb0-OcNvSvDKw4cMpVrQ0taexYeQ&s",
      "eScore": 76,
      "sScore": 9,
      "gScore": "15",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 2500
    },
    {
      "Name": "Workplace Condition Assessment (WCA)",
      "Website": "https://www.intertek.es/business-assurance/gestion-proveedores/auditoria-workplace-condition-assessment-wca/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKy81UOBXeUluSVV8I7kYUH9mdQxtYnd9d_w&s",
      "eScore": 68,
      "sScore": 14,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 4000
    },
    {
      "Name": "A.I.S.E",
      "Website": "https://www.aise.eu/",
      "Logo": "https://www.researchgate.net/publication/282891015/figure/fig3/AS:316672269008909@1452511961554/Product-logo-of-the-Charter-for-sustainable-cleaning-indicating-that-the-product-meets.png",
      "eScore": 46,
      "sScore": 16,
      "gScore": "38",
      "Price":100,
      "Lowest Price": 1170,
      "Highest Price": 0
    },
    {
      "Name": "Agricultura Org\u00e1nica - Uni\u00f3n Europea ",
      "Website": "https://agriculture.ec.europa.eu/farming/organic-farming_en",
      "Logo": "https://agriculture.ec.europa.eu/themes/contrib/oe_theme/dist/ec/images/logo/positive/logo-ec--en.svg",
      "eScore": 76,
      "sScore": 0,
      "gScore": "24",
      "Price":100,
      "Lowest Price": 277,
      "Highest Price": 925
    },
    {
      "Name": "Better Biomass (new name for the NTA 8080 Approved certificate)",
      "Website": "betterbiomass.com",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4nm7mFgwgEtYbgHUx0iTDwwQWJG2g9DtI1w&s",
      "eScore": 40,
      "sScore": 42,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 5000
    },
    {
      "Name": "BIOSPHERE DESTINATION COMMUNITY",
      "Website": "https://www.biospheresustainable.com/en",
      "Logo": "https://static.biospheresustainable.com/assets/img/web/Logo_BS_horizontal_color.svg?_=1719836855",
      "eScore": 1,
      "sScore": 63,
      "gScore": "35",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 3000
    },
    {
      "Name": "Biosphere Responsible Tourism",
      "Website": "https://www.biospheresustainable.com/en",
      "Logo": "https://static.biospheresustainable.com/assets/img/web/Logo_BS_horizontal_color.svg?_=1719836855",
      "eScore": 53,
      "sScore": 29,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 5000
    },
    {
      "Name": "bluesign\u00ae system",
      "Website": "bluesign\u00ae \u2014 Solutions and services for a sustainable textile industry - bluesign",
      "Logo": "https://www.sympatex.com/wp-content/uploads/2024/01/bluesign_header-1.png",
      "eScore": 44,
      "sScore": 25,
      "gScore": "31",
      "Price":100,
      "Lowest Price": 4615,
      "Highest Price": 18470
    },
    {
      "Name": "BRCGS Ethical Trade and Responsible Sourcing",
      "Website": "https://www.brcgs.com/our-standards/ethical-trade-and-responsible-sourcing/",
      "Logo": "https://agfocert.com/wp-content/uploads/ETRS-0-1024x190.jpg",
      "eScore": 4,
      "sScore": 83,
      "gScore": "14",
      "Price":100,
      "Lowest Price": 1390,
      "Highest Price": 2780
    },
    {
      "Name": "Cargill Triple S Soya Products",
      "Website": "https://www.cargill.com/sustainability",
      "Logo": "https://www.cargill.com/image/1432220384159/cargill-logo-header.png?v=1666700719000",
      "eScore": 42,
      "sScore": 46,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 1560,
      "Highest Price": 0
    },
    {
      "Name": "Certified Wildlife Friendly\u2122",
      "Website": "https://wildlifefriendly.org/",
      "Logo": "https://wildlifefriendly.org/wp-content/themes/wildlife/images/logo.png",
      "eScore": 76,
      "sScore": 8,
      "gScore": "16",
      "Price":100,
      "Lowest Price": 1850,
      "Highest Price": 1850
    },
    {
      "Name": "China Green Food",
      "Website": "http://www.greenfood.agri.cn/",
      "Logo": "http://www.greenfood.agri.cn/images/lssp2023_head1.png",
      "eScore": 72,
      "sScore": 0,
      "gScore": "28",
      "Price":100,
      "Lowest Price": 640,
      "Highest Price": 2550
    },
    {
      "Name": "Cradle to Cradle Certified Product Standard, Version 4.0 (Silver Level)",
      "Website": "https://c2ccertified.org/",
      "Logo": "https://toxservices.com/wp-content/uploads/2022/05/CradletoCradle_R_assessmentbody_rgb.jpg",
      "eScore": 44,
      "sScore": 32,
      "gScore": "23",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 0
    },
    {
      "Name": "EcoVadis",
      "Website": "https://ecovadis.com/",
      "Logo": "https://cdn.cookielaw.org/logos/c30d36b2-cf49-4b5c-bf4c-02a4539c08ce/553fb553-18d9-42b1-aef1-4632a233b978/6f17b74f-455f-412f-944a-e12c333585f0/logo-color.png",
      "eScore": 32,
      "sScore": 46,
      "gScore": "22",
      "Price":100,
      "Lowest Price": 460,
      "Highest Price": 4630
    },
    {
      "Name": "EU Ecolabel - Laundry Detergents",
      "Website": "https://environment.ec.europa.eu/topics/circular-economy/eu-ecolabel_en",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIzDUZOZd-DS9u8pFNSc8o6fj8OrbMupYxJQ&s\\",
      "eScore": 65,
      "sScore": 0,
      "gScore": "35",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 0
    },
    {
      "Name": "EU Ecolabel - Paper",
      "Website": "EU Ecolabel - Paper (europa.eu)",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIzDUZOZd-DS9u8pFNSc8o6fj8OrbMupYxJQ&s\\",
      "eScore": 86,
      "sScore": 0,
      "gScore": "14",
      "Price":100,
      "Lowest Price": 200,
      "Highest Price": 0
    },
    {
      "Name": "EU Ecolabel - Textiles",
      "Website": "EU Ecolabel - Clothing and Textiles (europa.eu)",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIzDUZOZd-DS9u8pFNSc8o6fj8OrbMupYxJQ&s\\",
      "eScore": 59,
      "sScore": 17,
      "gScore": "25",
      "Price":100,
      "Lowest Price": 600,
      "Highest Price": 0
    },
    {
      "Name": "EU Organic Farming",
      "Website": "https://agriculture.ec.europa.eu/farming/organic-farming_en",
      "Logo": "https://agriculture.ec.europa.eu/themes/contrib/oe_theme/dist/ec/images/logo/positive/logo-ec--en.svg",
      "eScore": 65,
      "sScore": 0,
      "gScore": "35",
      "Price":100,
      "Lowest Price": 185,
      "Highest Price": 925
    },
    {
      "Name": "Fair Labor Association- Principles of Responsible Sourcing and Production",
      "Website": "https://www.fairlabor.org/accountability/standards/manufacturing/mfg-principles/",
      "Logo": "https://www.fairlabor.org/wp-content/themes/fla/img/fla-anniversary-logo.png",
      "eScore": 2,
      "sScore": 84,
      "gScore": "4",
      "Price":100,
      "Lowest Price": 4630,
      "Highest Price": 0
    },
    {
      "Name": "Fair Labor Association- Workplace Code of Conduct and Compliance Benchmarks",
      "Website": "https://www.fairlabor.org/wp-content/uploads/2022/04/fla_workplace_compliance_benchmarks_rev_10.2020.pdf",
      "Logo": "https://www.fairlabor.org/wp-content/themes/fla/img/fla-anniversary-logo.png",
      "eScore": 5,
      "sScore": 90,
      "gScore": "5",
      "Price":100,
      "Lowest Price": 4630,
      "Highest Price": 13900
    },
    {
      "Name": "Food Safety System Certification 22000",
      "Website": "https://www.fssc.com/schemes/fssc-22000/",
      "Logo": "https://media.licdn.com/dms/image/D4D12AQGx6IUtcGL1Yg/article-cover_image-shrink_423_752/0/1705137629366?e=1725494400&v=beta&t=e5Ot4hH7DbHrLCisCBDyRLaiPVYHMb58vXnOwioa3Ao",
      "eScore": 16,
      "sScore": 5,
      "gScore": "79",
      "Price":100,
      "Lowest Price": 7800,
      "Highest Price": 0
    },
    {
      "Name": "FSSC 24000",
      "Website": "https://www.fssc.com/schemes/fssc-24000/become-fssc-24000-certified/",
      "Logo": "https://logowik.com/content/uploads/images/fssc-240004916.logowik.com.webp",
      "eScore": 0,
      "sScore": 87,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 7800,
      "Highest Price": 0
    },
    {
      "Name": "Global Organic Textile Standard - GOTS",
      "Website": "Home - GOTS - Global Organic Textile Standard (global-standard.org)",
      "Logo": "https://cdn.shopify.com/s/files/1/0497/1809/files/gotslogo_large.gif?17985187548554224389",
      "eScore": 29,
      "sScore": 44,
      "gScore": "27",
      "Price":100,
      "Lowest Price": 700,
      "Highest Price": 0
    },
    {
      "Name": "Global Red Meat Standard",
      "Website": "Home (grms.org)",
      "Logo": "https://findlogovector.com/wp-content/uploads/2022/05/global-red-meat-standard-grms-logo-vector-2022-xs.png",
      "eScore": 9,
      "sScore": 3,
      "gScore": "88",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 0
    },
    {
      "Name": "Global Seafood Alliance - Best Aquaculture Practices",
      "Website": "https://www.globalseafood.org/",
      "Logo": "https://www.globalseafood.org/assets/img/branding/gsa-logo-light.svg",
      "eScore": 28,
      "sScore": 21,
      "gScore": "51",
      "Price":100,
      "Lowest Price": 925,
      "Highest Price": 4630
    },
    {
      "Name": "Global Sustainable Tourism Criteria for Destinations",
      "Website": "https://www.gstcouncil.org/",
      "Logo": "https://www.oneplanetnetwork.org/sites/default/files/2021-12/org_62a4ff6d-35fb-eb11-94ef-000d3a4bf64b.PNG",
      "eScore": 45,
      "sScore": 33,
      "gScore": "22",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 0
    },
    {
      "Name": "Green Initiative",
      "Website": "https://greeninitiative.eco/",
      "Logo": "https://greeninitiative.eco/wp-content/uploads/2020/05/logo-green-initiative-3001002912222.png",
      "eScore": 100,
      "sScore": 0,
      "gScore": "0",
      "Price":100,
      "Lowest Price": 460,
      "Highest Price": 9230
    },
    {
      "Name": "Initiative for Compliance and Sustainability (ICS) Environmental Criteria",
      "Website": "https://ics-asso.org/",
      "Logo": "https://ics-asso.org/wp-content/uploads/2020/07/ICS_Logotypes_Couleur-3.jpg",
      "eScore": 61,
      "sScore": 18,
      "gScore": "21",
      "Price":100,
      "Lowest Price": 1500,
      "Highest Price": 0
    },
    {
      "Name": "Initiative for Compliance and Sustainability (ICS) Social Criteria",
      "Website": "https://ics-asso.org/",
      "Logo": "https://ics-asso.org/wp-content/uploads/2020/07/ICS_Logotypes_Couleur-3.jpg",
      "eScore": 7,
      "sScore": 77,
      "gScore": "16",
      "Price":100,
      "Lowest Price": 2500,
      "Highest Price": 0
    },
    {
      "Name": "ISCC EU",
      "Website": "https://www.iscc-system.org/",
      "Logo": "https://www.iscc-system.org/wp-content/uploads/2023/02/ISCC-blue-logo-1024x614.png",
      "eScore": 39,
      "sScore": 43,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 0
    },
    {
      "Name": "ISCC PLUS",
      "Website": "https://www.iscc-system.org/",
      "Logo": "https://www.iscc-system.org/wp-content/uploads/2023/02/ISCC-blue-logo-1024x614.png",
      "eScore": 36,
      "sScore": 41,
      "gScore": "23",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 0
    },
    {
      "Name": "ISCC PLUS - Voluntary Add-ons",
      "Website": "https://www.iscc-system.org/",
      "Logo": "https://www.iscc-system.org/wp-content/uploads/2023/02/ISCC-blue-logo-1024x614.png",
      "eScore": 44,
      "sScore": 38,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 500,
      "Highest Price": 1000
    },
    {
      "Name": "KRAV",
      "Website": "Eat Better with KRAV - a Label for Sustainable Food",
      "Logo": "https://www.ccpb.it/wp-content/uploads/2017/08/KRAV.png",
      "eScore": 49,
      "sScore": 18,
      "gScore": "33",
      "Price":100,
      "Lowest Price": 2340,
      "Highest Price": 0
    },
    {
      "Name": "Nature Care Products Standard",
      "Website": "https://gfaw.eu/en/ncp/",
      "Logo": "https://gfaw.eu/wp-content/uploads/2022/12/GfaW_NCP_Label_pur_RGB.png",
      "eScore": 68,
      "sScore": 2,
      "gScore": "30",
      "Price":100,
      "Lowest Price": 1560,
      "Highest Price": 0
    },
    {
      "Name": "Naturland Fair",
      "Website": "https://www.naturland.de/en/producers/fair-en.html",
      "Logo": NaN,
      "eScore": 45,
      "sScore": 37,
      "gScore": "17",
      "Price":100,
      "Lowest Price": 2200,
      "Highest Price": 0
    },
    {
      "Name": "Org\u00e1nica - Uni\u00f3n Europea",
      "Website": "Producci\u00f3n y productos ecol\u00f3gicos - Comisi\u00f3n Europea (europa.eu)",
      "Logo": "https://agriculture.ec.europa.eu/themes/contrib/oe_theme/dist/ec/images/logo/positive/logo-ec--en.svg",
      "eScore": 76,
      "sScore": 0,
      "gScore": "24",
      "Price":100,
      "Lowest Price": 277,
      "Highest Price": 925
    },
    {
      "Name": "Origin Green Sustainable Dairy Assurance Standard",
      "Website": "https://www.origingreen.ie/",
      "Logo": "https://www.st-tola.ie/sites/st-tola.ie/files/styles/full_saint/public/origin_green_back.jpg?itok=opb-Nwzu",
      "eScore": 54,
      "sScore": 17,
      "gScore": "29",
      "Price":100,
      "Lowest Price": 200,
      "Highest Price": 600
    },
    {
      "Name": "ProTerra Europe",
      "Website": "https://www.proterrafoundation.org/",
      "Logo": "https://www.proterrafoundation.org/wp-content/uploads/2020/10/ProTerra-Foundation.png",
      "eScore": 43,
      "sScore": 43,
      "gScore": "14",
      "Price":100,
      "Lowest Price": 3900,
      "Highest Price": 0
    },
    {
      "Name": "ProTerra Foundation",
      "Website": "https://www.proterrafoundation.org/",
      "Logo": "https://www.proterrafoundation.org/wp-content/uploads/2020/10/ProTerra-Foundation.png",
      "eScore": 45,
      "sScore": 40,
      "gScore": "15",
      "Price":100,
      "Lowest Price": 3900,
      "Highest Price": 0
    },
    {
      "Name": "REDcert-EU",
      "Website": "https://www.redcert.org/",
      "Logo": "https://www.redcert.org/images/Logo/REDcert_Logo_120x77px.png",
      "eScore": 63,
      "sScore": 18,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 0
    },
    {
      "Name": "REDcert\u00b2",
      "Website": "https://www.redcert.org/",
      "Logo": "https://www.redcert.org/images/Logo/REDcert_Logo_120x77px.png",
      "eScore": 63,
      "sScore": 18,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 2000,
      "Highest Price": 0
    },
    {
      "Name": "regio.garantie",
      "Website": "https://www.regio-garantie.ch/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBhwmFvyTQ7ydR_0EhpTmIyGq7bAMtM6Dv_g&s",
      "eScore": 14,
      "sScore": 29,
      "gScore": "57",
      "Price":100,
      "Lowest Price": 1300,
      "Highest Price": 0
    },
    {
      "Name": "Responsible Business Alliance (RBA)",
      "Website": "https://www.responsiblebusiness.org/",
      "Logo": "https://www.responsiblebusiness.org/media/rba-home-logo.svg",
      "eScore": 20,
      "sScore": 59,
      "gScore": "21",
      "Price":100,
      "Lowest Price": 925,
      "Highest Price": 0
    },
    {
      "Name": "Responsible Jewellery Council (RJC)",
      "Website": "https://www.responsiblejewellery.com/",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKb2NY_MvosS6nN-1IkLUC-47kgDyVYCXegw&s",
      "eScore": 19,
      "sScore": 59,
      "gScore": "22",
      "Price":100,
      "Lowest Price": 200,
      "Highest Price": 0
    },
    {
      "Name": "Round Table on Responsible Soy Association - RTRS",
      "Website": "https://responsiblesoy.org/",
      "Logo": "https://responsiblesoy.org/wp-content/uploads/2021/06/RTRS-logo-2021.svg",
      "eScore": 46,
      "sScore": 44,
      "gScore": "10",
      "Price":100,
      "Lowest Price": 2780,
      "Highest Price": 4630
    },
    {
      "Name": "Singapore Green Labelling Scheme",
      "Website": "Singapore Green Labelling Scheme - Singapore Environment Council (sec.org.sg)",
      "Logo": "https://topkrete.com/wp-content/uploads/2022/11/GreenLabel-logo-External-Use_GreenLabel-Logo-300x300.png",
      "eScore": 52,
      "sScore": 22,
      "gScore": "26",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 0
    },
    {
      "Name": "Social Accountability International - SA8000",
      "Website": "https://sa-intl.org/",
      "Logo": "https://sa-intl.org/wp-content/uploads/2020/03/sai-logo-rev-768x180-1.png",
      "eScore": 0,
      "sScore": 89,
      "gScore": "11",
      "Price":100,
      "Lowest Price": 9260,
      "Highest Price": 0
    },
    {
      "Name": "Sustainable Biomass Program (SBP)",
      "Website": "https://sbp-cert.org/",
      "Logo": "https://www.isealalliance.org/sites/default/files/2021-09/SBP_Logo_resized20Community20website.png",
      "eScore": 45,
      "sScore": 38,
      "gScore": "16",
      "Price":100,
      "Lowest Price": 277,
      "Highest Price": 925
    },
    {
      "Name": "TerraChoice -EcoLogo Program (UL Ecologo Certification)",
      "Website": "https://www.ul.com/resources/ecologo-certification-program",
      "Logo": "https://www.ul.com/sites/default/files/inline-images/EL-UL2700-Mark-Mock-Up.png",
      "eScore": 52,
      "sScore": 28,
      "gScore": "20",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 0
    },
    {
      "Name": "The Blue Angel - Computer",
      "Website": "https://www.blauer-engel.de/en/productworld/computers-and-keyboards",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJUAVdkys-SrMB33V811mT8PO6ybLskSpgfg&s",
      "eScore": 31,
      "sScore": 0,
      "gScore": "69",
      "Price":100,
      "Lowest Price": 400,
      "Highest Price": 0
    },
    {
      "Name": "The Blue Angel - Paper",
      "Website": "https://www.blauer-engel.de/en",
      "Logo": "https://www.blauer-engel.de/themes/custom/be/dist/images/logo_en.svg",
      "eScore": 78,
      "sScore": 0,
      "gScore": "22",
      "Price":100,
      "Lowest Price": 400,
      "Highest Price": 0
    },
    {
      "Name": "The Blue Angel - Textiles",
      "Website": "https://www.blauer-engel.de/en/publications/detail/blue-angel-textiles",
      "Logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJUAVdkys-SrMB33V811mT8PO6ybLskSpgfg&s",
      "eScore": 58,
      "sScore": 32,
      "gScore": "10",
      "Price":100,
      "Lowest Price": 3900,
      "Highest Price": 0
    },
    {
      "Name": "The European Ecotourism Labelling Standard",
      "Website": "https://www.ecotourism-network.eu/",
      "Logo": "https://www.ecotourism-network.eu/wp-content/uploads/2022/05/site_logo.png",
      "eScore": 50,
      "sScore": 31,
      "gScore": "19",
      "Price":100,
      "Lowest Price": 1000,
      "Highest Price": 0
    },
    {
      "Name": "The Gold Standard",
      "Website": "https://www.goldstandard.org/",
      "Logo": "https://images.prismic.io/goldstandard/64638d52-d9fc-488e-852b-f0cf546a0ce9_Gold+Standard+Logo.svg?q=90",
      "eScore": 19,
      "sScore": 63,
      "gScore": "18",
      "Price":100,
      "Lowest Price": 4630,
      "Highest Price": 0
    },
    {
      "Name": "Verified Carbon Standard - VCS",
      "Website": "https://verra.org/programs/verified-carbon-standard/",
      "Logo": "https://verra.org/wp-content/uploads/2022/08/Verra-Logo.svg",
      "eScore": 58,
      "sScore": 29,
      "gScore": "13",
      "Price":100,
      "Lowest Price": 460,
      "Highest Price": 925
    },
    {
      "Name": "Zerya",
      "Website": "https://zerya.org/",
      "Logo": "https://araberries.es/wp-content/uploads/2018/09/logo-Zerya.png",
      "eScore": 50,
      "sScore": 7,
      "gScore": "43",
      "Price":100,
      "Lowest Price": 1850,
      "Highest Price": 9260
    },
    {
      "Name": "ZNU Standard - driving sustainable change",
      "Website": "https://www.mehrwert-nachhaltigkeit.de/en/",
      "Logo": "https://www.mehrwert-nachhaltigkeit.de/fileadmin/_processed_/e/2/csm_znu-standard-logo_5344f6edc5.png",
      "eScore": 31,
      "sScore": 34,
      "gScore": "35",
      "Price":100,
      "Lowest Price": 2780,
      "Highest Price": 0
    }
  ]


export default certificate_3rd;